import { StyleSheet } from 'react-native';
import { theme } from './theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    navBar: {
        height: 50,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: theme.spacing.lg,
        borderBottomWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.card,
    },
    backButton: {
        paddingVertical: 6,
    },
    backButtonText: {
        color: theme.colors.primary,
        fontSize: 16,
        fontWeight: '700',
    },
    favoriteButton: {
        padding: 6,
        justifyContent: 'center',
        alignItems: 'center',
    },
    favoriteIcon: {
        fontSize: 22,
    },
    scrollContainer: {
        paddingBottom: 100,
    },
    carouselContainer: {
        position: 'relative',
        height: 330,
        backgroundColor: theme.colors.card,
        borderBottomWidth: 1,
        borderColor: theme.colors.border,
    },
    imageWrapper: {
        height: 300,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.colors.card,
    },
    carouselImage: {
        width: '90%',
        height: '100%',
    },
    arrowButton: {
        position: 'absolute',
        top: '40%',
        width: 40,
        height: 40,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
        zIndex: 10,
    },
    leftArrow: {
        left: theme.spacing.md,
    },
    rightArrow: {
        right: theme.spacing.md,
    },
    arrowText: {
        fontSize: 28,
        fontWeight: '300',
        color: theme.colors.text,
        marginTop: -3,
    },
    arrowDisabled: {
        color: theme.colors.textMuted,
        opacity: 0.4,
    },
    paginationContainer: {
        position: 'absolute',
        bottom: 10,
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        height: 20,
    },
    paginationDot: {
        height: 6,
        borderRadius: 3,
        marginHorizontal: 4,
    },
    paginationDotActive: {
        width: 16,
        backgroundColor: theme.colors.primary,
    },
    paginationDotInactive: {
        width: 6,
        backgroundColor: theme.colors.border,
    },
    infoContainer: {
        padding: theme.spacing.lg,
        backgroundColor: theme.colors.card,
        margin: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    brand: {
        fontSize: 10,
        color: theme.colors.textMuted,
        textTransform: 'uppercase',
        fontWeight: '800',
        letterSpacing: 0.5,
        marginBottom: 4,
    },
    title: {
        fontSize: 20,
        fontWeight: '800',
        color: theme.colors.text,
        marginBottom: theme.spacing.sm,
    },
    priceRow: {
        flexDirection: 'row',
        alignItems: 'baseline',
        marginBottom: theme.spacing.sm,
    },
    price: {
        fontSize: 24,
        fontWeight: '800',
        color: theme.colors.text,
    },
    discountPrice: {
        fontSize: 24,
        fontWeight: '800',
        color: theme.colors.danger,
        marginRight: 10,
    },
    originalPrice: {
        fontSize: 16,
        color: theme.colors.textMuted,
        textDecorationLine: 'line-through',
    },
    stockBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: theme.spacing.md,
        paddingVertical: 4,
        borderRadius: theme.borderRadius.round,
        alignSelf: 'flex-start',
        marginTop: theme.spacing.xs,
    },
    stockIn: {
        backgroundColor: theme.colors.successLight,
    },
    stockOut: {
        backgroundColor: theme.colors.dangerLight,
    },
    stockDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        marginRight: 6,
    },
    stockText: {
        fontSize: 11,
        fontWeight: '700',
    },
    divider: {
        height: 1,
        backgroundColor: theme.colors.border,
        marginVertical: theme.spacing.lg,
    },
    sectionTitle: {
        fontSize: 15,
        fontWeight: '800',
        color: theme.colors.text,
        marginBottom: theme.spacing.sm,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    description: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        lineHeight: 22,
    },
    center: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.colors.background,
    },
    errorText: {
        fontSize: 16,
        color: theme.colors.danger,
        fontWeight: '600',
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 80,
        borderTopWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.card,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: theme.spacing.lg,
        justifyContent: 'space-between',
        ...theme.shadows.lg,
    },
    quantitySelector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.background,
        borderRadius: theme.borderRadius.md,
        padding: 4,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    qtyButton: {
        width: 36,
        height: 36,
        justifyContent: 'center',
        alignItems: 'center',
    },
    qtyText: {
        fontSize: 20,
        fontWeight: '700',
        color: theme.colors.text,
    },
    qtyNumber: {
        marginHorizontal: theme.spacing.md,
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.text,
    },
    addButton: {
        flex: 1,
        backgroundColor: theme.colors.primary,
        marginLeft: theme.spacing.lg,
        height: 48,
        borderRadius: theme.borderRadius.md,
        justifyContent: 'center',
        alignItems: 'center',
        ...theme.shadows.sm,
    },
    disabledButton: {
        backgroundColor: theme.colors.border,
    },
    addButtonText: {
        color: theme.colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
});