import { StyleSheet } from 'react-native';
import { theme } from './theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.colors.background,
    },
    centerContainerScroll: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingVertical: theme.spacing.xl,
    },
    loginForm: {
        padding: theme.spacing.xl,
        backgroundColor: theme.colors.card,
        marginHorizontal: theme.spacing.lg,
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.md,
    },
    title: {
        fontSize: 22,
        fontWeight: '800',
        color: theme.colors.text,
        marginBottom: 6,
    },
    subtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginBottom: theme.spacing.xl,
        lineHeight: 20,
    },
    inputGroup: {
        marginBottom: theme.spacing.md,
    },
    label: {
        fontSize: 11,
        fontWeight: '800',
        color: theme.colors.textSecondary,
        marginBottom: theme.spacing.xs,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    input: {
        height: 46,
        backgroundColor: theme.colors.background,
        borderRadius: theme.borderRadius.md,
        paddingHorizontal: theme.spacing.md,
        fontSize: 15,
        color: theme.colors.text,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    loginBtn: {
        backgroundColor: theme.colors.primary,
        height: 48,
        borderRadius: theme.borderRadius.md,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: theme.spacing.sm,
        ...theme.shadows.sm,
    },
    loginBtnDisabled: {
        backgroundColor: theme.colors.primaryLight,
    },
    loginBtnText: {
        color: theme.colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
    switchModeContainer: {
        marginTop: theme.spacing.lg,
        alignItems: 'center',
    },
    switchModeText: {
        color: theme.colors.primary,
        fontSize: 14,
        fontWeight: '600',
    },
    /* ESTILOS PERFIL ACTIVO */
    profileBox: {
        backgroundColor: theme.colors.card,
        margin: theme.spacing.lg,
        padding: theme.spacing.xl,
        borderRadius: theme.borderRadius.lg,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.md,
    },
    avatar: {
        fontSize: 50,
        marginBottom: theme.spacing.sm,
    },
    welcomeText: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        fontWeight: '500',
    },
    usernameText: {
        fontSize: 22,
        fontWeight: '800',
        color: theme.colors.text,
        marginTop: 4,
    },
    emailText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginTop: 2,
    },
    divider: {
        height: 1,
        backgroundColor: theme.colors.border,
        width: '100%',
        marginVertical: theme.spacing.lg,
    },
    logoutBtn: {
        borderColor: theme.colors.danger,
        borderWidth: 1.5,
        width: '100%',
        height: 46,
        borderRadius: theme.borderRadius.md,
        justifyContent: 'center',
        alignItems: 'center',
    },
    logoutBtnText: {
        color: theme.colors.danger,
        fontSize: 15,
        fontWeight: '700',
    },
    scrollContent: {
        paddingBottom: theme.spacing.xxl,
    },
    favoritesSection: {
        marginHorizontal: theme.spacing.lg,
        marginBottom: theme.spacing.lg,
    },
    sectionHeader: {
        fontSize: 16,
        fontWeight: '800',
        color: theme.colors.text,
        marginBottom: theme.spacing.md,
        letterSpacing: 0.2,
    },
    favLoader: {
        marginVertical: theme.spacing.lg,
    },
    emptyFavsBox: {
        backgroundColor: theme.colors.card,
        borderRadius: theme.borderRadius.lg,
        padding: theme.spacing.xl,
        alignItems: 'center',
        borderStyle: 'dashed',
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    emptyFavsText: {
        fontSize: 14,
        fontWeight: '700',
        color: theme.colors.textSecondary,
    },
    emptyFavsSubtext: {
        fontSize: 12,
        color: theme.colors.textMuted,
        textAlign: 'center',
        marginTop: 4,
    },
    favCard: {
        backgroundColor: theme.colors.card,
        borderRadius: theme.borderRadius.lg,
        padding: theme.spacing.sm,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: theme.spacing.sm,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    favImageContainer: {
        backgroundColor: '#fafafa',
        padding: theme.spacing.xs,
        borderRadius: theme.borderRadius.md,
    },
    favImage: {
        width: 50,
        height: 50,
        borderRadius: theme.borderRadius.sm,
    },
    favInfo: {
        flex: 1,
        marginLeft: theme.spacing.md,
        justifyContent: 'center',
    },
    favBrand: {
        fontSize: 9,
        color: theme.colors.textMuted,
        fontWeight: '800',
        textTransform: 'uppercase',
    },
    favTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.text,
        marginTop: 2,
    },
    favPriceRow: {
        flexDirection: 'row',
        alignItems: 'baseline',
        marginTop: 4,
    },
    favPrice: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.text,
    },
    favDiscountPrice: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.danger,
        marginRight: 6,
    },
    favOriginalPrice: {
        fontSize: 11,
        color: theme.colors.textMuted,
        textDecorationLine: 'line-through',
    },
    deleteFavBtn: {
        padding: theme.spacing.sm,
        justifyContent: 'center',
        alignItems: 'center',
    },
    deleteFavText: {
        fontSize: 18,
    },
    /* ESTILOS PARA ÓRDENES */
    ordersSection: {
        marginHorizontal: theme.spacing.lg,
        marginBottom: theme.spacing.lg,
    },
    orderLoader: {
        marginVertical: theme.spacing.lg,
    },
    emptyOrdersBox: {
        backgroundColor: theme.colors.card,
        borderRadius: theme.borderRadius.lg,
        padding: theme.spacing.xl,
        alignItems: 'center',
        borderStyle: 'dashed',
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    emptyOrdersText: {
        fontSize: 14,
        fontWeight: '700',
        color: theme.colors.textSecondary,
    },
    emptyOrdersSubtext: {
        fontSize: 12,
        color: theme.colors.textMuted,
        textAlign: 'center',
        marginTop: 4,
    },
    orderCard: {
        backgroundColor: theme.colors.card,
        borderRadius: theme.borderRadius.lg,
        padding: theme.spacing.lg,
        marginBottom: theme.spacing.sm,
        borderWidth: 1,
        borderColor: theme.colors.border,
        ...theme.shadows.sm,
    },
    orderHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        borderBottomWidth: 1,
        borderColor: theme.colors.border,
        paddingBottom: theme.spacing.sm,
        marginBottom: theme.spacing.sm,
    },
    orderIdText: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.text,
    },
    orderDateText: {
        fontSize: 11,
        color: theme.colors.textMuted,
        marginTop: 2,
    },
    statusBadge: {
        paddingHorizontal: theme.spacing.sm,
        paddingVertical: 3,
        borderRadius: theme.borderRadius.sm,
    },
    statusBadgeText: {
        fontSize: 9,
        fontWeight: '800',
        textTransform: 'uppercase',
    },
    orderItemsList: {
        marginBottom: theme.spacing.md,
    },
    orderItemText: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        lineHeight: 18,
    },
    orderFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTopWidth: 1,
        borderColor: theme.colors.border,
        paddingTop: theme.spacing.sm,
    },
    orderTotalLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.textSecondary,
    },
    orderTotalValue: {
        fontSize: 15,
        fontWeight: '800',
        color: theme.colors.primary,
    },
});